### PR TITLE
update to level@4 and remove deferred-leveldown

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Ah, should have commented here instead. @karissa Why not `level@5`? It's based on `leveldown@5` which now is based on N-API (also has prebuilts for arm and working on getting prebuilts for mobile as well).

**Comment by okdistribute** [comment]
not sure, @noffle @gmaclennan have been working on that part lately and said level 4 was working, not sure what the story is in regard to 5

**Comment by hackergrrl** [comment]
ha, level@5 is a whole [11 hours old](https://github.com/Level/level/releases/tag/v5.0.0) ;)

**Comment by ralphtheninja** [comment]
@karissa Maybe you can pull in `level5` later.

@noffle :grin:

**Comment by okdistribute** [comment]
heheh

**Comment by hackergrrl** [comment]
yay so much simpler :tada: :taco:

**Review by hackergrrl — APPROVED** [review]

**Pull request merged**
